version: 2
jobs:
  build:
    parallelism: 1
    docker:
      # specify the version you desire here
      - image: circleci/node:12.3.1-browsers-legacy

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ arch}}-{{ .Branch }}-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ arch}}-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Generate our medium feed
          command: yarn feed

      - run:
          name: Generate sheets
          command: yarn sheets
      - run:
          name: Generate icons
          command: yarn mdi
      - run:
          name: Generate our routes
          command: yarn route
      - run:
          name: Generate static files
          command: yarn generate

      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run production
            fi
            if [ "${CIRCLE_BRANCH}" == "staging" ]; then
              yarn run staging
            fi
            #if [ "${CIRCLE_BRANCH}" == "dev" ]; then
            #  yarn run development
            #fi
